name = "LJsimulation"
uuid = "f847f8e0-37bd-4b88-ab76-710286f346cf"
authors = ["jpspadeto <jpspadeto@gmail.com> and contributors"]
version = "0.1.3"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
