name = "LJsimulation"
uuid = "f847f8e0-37bd-4b88-ab76-710286f346cf"
authors = ["jpspadeto <jpspadeto@gmail.com> and contributors"]
version = "0.1.1"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
